---

- name: set up docker host
  hosts: docker-host.lan.bendaschel.com
  tasks:
    - name: Create apps user
      ansible.builtin.user:
        name: apps
        shell: /bin/bash
        uid: 1001

    - name: copy smb credentials
      copy:
        src: secrets/smb-paperless-creds
        dest: /home/apps/.smb-paperless-creds

    - name: install cifs-utils
      community.general.apk:
        name: "cifs-utils"
        update_cache: yes

    - name: mount media directory
      ansible.posix.mount:
        path: /mnt/media
        src: //media-nas.lan.bendaschel.com/media
        fstype: cifs
        opts: uid=1000,gid=1000,rw,file_mode=0775,dir_mode=0775,guest
        state: present

    - name: create mount points
      file:
        state: directory
        path: /mnt/apps/paperless
        recurse: true

    - name: mount paperless directory
      ansible.posix.mount:
        path: /mnt/apps/paperless
        src: //badassnasng.lan.bendaschel.com/paperless
        fstype: cifs
        opts: uid=1001,gid=1001,rw,file_mode=0775,dir_mode=0775,credentials=/home/apps/.smb-paperless-creds
        state: present

    - name: make dirs for docker compose
      file:
        state: directory
        path: /opt/services/paperless

    - name: copy docker compose files
      copy:
        src: files/paperless/docker-compose.yml
        dest: /opt/services/paperless/docker-compose.yml

    - name: docker compose paperless
      community.docker.docker_compose:
        project_src: /opt/services/paperless
        state: present
