---

- name: set up docker host
  hosts: docker-host.lan.bendaschel.com
  tasks:
    - name: Create apps user
      ansible.builtin.user:
        name: apps
        shell: /bin/bash
        uid: 1001

    - name: install cifs-utils
      community.general.apk:
        name: "cifs-utils"
        update_cache: yes

    - name: mount media directory
      ansible.posix.mount:
        path: /mnt/media
        src: //media-nas.lan.bendaschel.com/media
        fstype: cifs
        opts: uid=1000,gid=1000,rw,file_mode=0775,dir_mode=0775,guest
        state: present

    - name: make dirs for docker compose
      file:
        state: directory
        path: /opt/services/paperless

    - name: make dirs for docker compose
      file:
        state: directory
        path: /opt/services/uptime-kuma

    - name: copy docker compose files for paperless
      copy:
        src: files/paperless/docker-compose.yml
        dest: /opt/services/paperless/docker-compose.yml

    - name: copy docker compose files for uptime kuma
      copy:
        src: files/uptime-kuma/docker-compose.yml
        dest: /opt/services/uptime-kuma/docker-compose.yml

    - name: copy docker compose env file
      copy:
        src: files/paperless/.env
        dest: /opt/services/paperless/.env

    - name: docker compose paperless
      community.docker.docker_compose:
        project_src: /opt/services/paperless
        state: present

    - name: docker compose uptime kuma
      community.docker.docker_compose:
        project_src: /opt/services/uptime-kuma
        state: present