---

version: '3'
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '15000:15000/udp'
      - '15777:15777/udp'
    volumes:
      - satisfactory_data:/config
    environment:
      - MAXPLAYERS=8
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 6G
  file_browser:
    image: 'filebrowser/filebrowser'
    volumes:
      - satisfactory_data:/srv
      - ./filebrowser.db:/filebrowser.db
      - ./filebrowser.json:/.filebrowser.json
    ports:
      - '8787:80'
volumes:
  satisfactory_data: