---

- name: set up docker host
  hosts: docker-hosts
  roles:
    - docker-host
  tags:
    - docker

- name: set up NAS
  hosts: nas
  roles:
    - nas
  tags:
    - nas

- name: set up ARM
  hosts: arm
  roles:
    - ripper
  tags:
    - arm