---

version: "3.7"

services:
  proxy:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_config:/config
      - caddy_data:/data
    env_file:
      - .env
volumes:
  caddy_data:
  caddy_config: