---
version: '3.7'

services:

  torrent:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    env_file:
      - .env
    volumes:
      - transmission_config:/config
      - downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped


volumes:
  transmission_config:
  downloads:
    driver_opts:
      type: cifs
      device: "${SMB_SHARE}/media"
      o: "addr=badassnasng.lan.bendaschel.com,uid=1000,gid=1000,rw,file_mode=0775,dir_mode=0775,username=${SMB_USER},password=${SMB_PASSWORD}"
