---
version: "3.7"

services:
  uptime:
    image: louislam/uptime-kuma:alpine
    restart: unless-stopped
    ports:
      - "8765:3001"
    volumes:
      - uptime_kuma_data:/app/data

volumes:
  uptime_kuma_data: