---
version: "3.7"

services:

  portainer:
    image: "cr.portainer.io/portainer/portainer-ce:2.11.1"
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  portainer_data:
