---
version: "3.7"

services:
  portainer:
    image: "cr.portainer.io/portainer/portainer-ce:2.9.3"
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data: