---

version: "3.7"

services:
  unifi:
    image: "lscr.io/linuxserver/unifi-controller"
    restart: unless-stopped
    volumes:
      - unifi_data:/config
    network_mode: host
    networks:
      host:

  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - "PLEX_CLAIM=${PLEX_CLAIM}"
    networks:
      - host
    volumes:
      - plex_library:/config
      - /mnt/media:/media
    restart: unless-stopped

volumes:
  unifi_data:
  pihole_etc:
  pihole_dnsmasq:
  plex_library:
    driver_opts:
      type: cifs
      device: "${SMB_SHARE}/MEDIA"
      o: "addr=badassnasng.lan.bendaschel.com,uid=${USERMAP_UID},gid=${USERMAP_GID},rw,file_mode=0777,dir_mode=0775,username=${SMB_USER},password=${SMB_PASSWORD}"
  lets_encrypt_data:
  proxy_manager_data:

networks:
  host:
    name: host
    external: true