---

version: "3.7"

services:
  unifi:
    image: "lscr.io/linuxserver/unifi-controller"
    restart: unless-stopped
    volumes:
      - unifi_data:/config
    network_mode: host
    networks:
      host:

  pihole:
    image: "pihole/pihole:latest"
    restart: unless-stopped
    environment:
      - "TZ=${TZ}"
      - "WEBPASSWORD=${PIHOLE_ADMIN_PW}"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8888:80/tcp"
    volumes:
      - 'pihole_etc:/etc/pihole/'
      - 'pihole_dnsmasq:/etc/dnsmasq.d/'
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - "PLEX_CLAIM=${PLEX_CLAIM}"
    networks:
      - host
    volumes:
      - plex_library:/config
      - /mnt/media:/media
    restart: unless-stopped

  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - proxy_manager_data:/data
      - lets_encrypt_data:/etc/letsencrypt
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
volumes:
  unifi_data:
  pihole_etc:
  pihole_dnsmasq:
  plex_library:
  lets_encrypt_data:
  proxy_manager_data:

networks:
  host:
    name: host
    external: true