---

version: "3.7"

services:
  unifi:
    image: "lscr.io/linuxserver/unifi-controller"
    restart: unless-stopped
    volumes:
      - unifi_data:/config
    ports:
    - "3478:3478/udp"
    - "10001:10001/udp"
    - "8080:8080"
    - "8443:8443"
    - "1900:1900/udp"
    - "8843:8843"
    - "8880:8880"
    - "6789:6789"
    - "5514:5514/udp"
  pihole:
    image: "pihole/pihole:latest"
    restart: unless-stopped
    environment:
      - "TZ=${TZ}"
      - "WEBPASSWORD=${PIHOLE_ADMIN_PW}"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8888:80/tcp"
    volumes:
      - 'pihole_etc:/etc/pihole/'
      - 'pihole_dnsmasq:/etc/dnsmasq.d/'
volumes:
  unifi_data:
  pihole_etc:
  pihole_dnsmasq: