---
version: "3.7"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - home_assistant_data:/config
    restart: unless-stopped
volumes:
  home_assistant_data: