version: '3.8'

services:
  proxy:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  database:
    image: mariadb:10.5
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/srv/pterodactyl/database:/var/lib/mysql"
    env_file:
      - .env
  cache:
    image: redis:alpine
    restart: unless-stopped
    env_file:
      - .env
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: unless-stopped
    env_file:
      - .env
    links:
      - database
      - cache
    volumes:
      - "/srv/pterodactyl/var/:/app/var/"
      - "/srv/pterodactyl/nginx/:/etc/nginx/http.d/"
      - "/srv/pterodactyl/certs/:/etc/letsencrypt/"
      - "/srv/pterodactyl/logs/:/app/storage/logs"

volumes:
  caddy_data:
  caddy_config:


networks:
  default:
    ipam:
      config:
        - subnet: 172.31.0.0/16
