---

- name: users | Capturing Existing Users
  uri:
    force_basic_auth: true
    method: GET
    password: "{{ freenas_password }}"
    return_content: true
    url: "{{ freenas_api_url + '/api/v2.0/user/' }}"
    user: "{{ freenas_user }}"
  register: freenas_users_found
  delegate_to: localhost
  tags:
    - freenas_users

- name: users | Setting Users Config Fact
  set_fact:
    freenas_users_config: "{{ lookup('template', 'users_config.yaml.j2') }}"
  tags:
    - freenas_users

- name: users | Creating Users
  uri:
    body: "{{ item }}"
    body_format: json
    force_basic_auth: true
    method: POST
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 200
    url: "{{ freenas_api_url + '/api/v2.0/user/' }}"
    user: "{{ freenas_user }}"
  delegate_to: localhost
#  no_log: true
  with_items: "{{ freenas_users_config['create_users'] }}"
  tags:
    - freenas_users

- name: users | Updating Users
  uri:
    body:
      password: "{{ item['config']['password'] | default(omit) }}"
    body_format: json
    force_basic_auth: true
    method: PUT
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 200
    url: "{{ freenas_api_url + '/api/v2.0/user/id/' + item['id']|string + '/' }}"
    user: "{{ freenas_user }}"
  delegate_to: localhost
  with_items: "{{ freenas_users_config['update_users'] }}"
  tags:
    - freenas_users

- name: users | Deleting Users
  uri:
    force_basic_auth: true
    method: DELETE
    password: "{{ freenas_password }}"
    return_content: true
    status_code: 204
    url: "{{ freenas_api_url + '/api/v2.0/user/' + item|string + '/' }}"
    user: "{{ freenas_user }}"
  delegate_to: localhost
  with_items: "{{ freenas_users_config['delete_users'] }}"
  tags:
    - freenas_users
