---

- name: Create Groups
  ansible.builtin.group:
    name: '{{ item.group | default(item.name) }}'
  with_items: '{{ nas_users }}'

- name: Create NAS users
  ansible.builtin.user:
    name: '{{ item.name }}'
    group: '{{ item.group | default(item.name) }}'
  with_items: '{{ nas_users }}'

